### ISSUE TITLE
Panic at UnrecognizedArchitecture("native")', src/zig.rs:338:46

### ISSUE THREAD

**Issue by konstin** [messense/cargo-zigbuild#44]
I had previously used zig cc with `zig cc -target native-native-gnu.2.17 $@`. If i try the same with cargo-zigbuild, I'm getting a panic:

```
$ cargo zigbuild --target native-native-gnu.2.17
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnrecognizedArchitecture("native")', src/zig.rs:338:46
```

**Comment by messense** [comment]
This is expected since the `--target` option is designed for cargo targets not zig targets. To support `native-native-gnu` we'd need to translate it to cargo target before feeding to [`target-lexicon`](https://docs.rs/target-lexicon/latest/target_lexicon/index.html).

Although it should give a better error message instead of panic.

**Comment by messense** [comment]
Fixed the panic in b1b7a3e8c65ef642fcc014d4c6c57bc734811b17, I don't think it's worth it to support `native-native-gnu` here since we need to pass the target down to `cargo` and translate it to host target triple is quite involved given the operating systems and libc variants combinations.

**Comment by konstin** [comment]
not sure if that's possible, but it would be neat if `native-native-gnu` would translate to not passing a `--target` to cargo on a glibc linux

**Comment by konstin** [comment]
Also thanks for fixing this so quickly!
